import math

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
ROAD_WIDTH = 200
ROAD_WIDTH_M = 7.0 # meters
CAR_WIDTH = 40
CAR_LENGTH = 60
CAR_WHEELBASE = 40
CAR_SPEED = 5.0  # initial ego speed (pixels/frame)
LANE_LINE_WIDTH = 5
LANE_DASH_LENGTH = 40
LANE_GAP = 20

D_HEADING = math.pi/12
RESOLUTION = 20
TURNING_RADIUS = RESOLUTION/D_HEADING

PIXELS_PER_METER = ROAD_WIDTH / ROAD_WIDTH_M
METERS_PER_PIXEL = ROAD_WIDTH_M / ROAD_WIDTH